apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    # Tell the NGINX controller that the paths are regexes
    nginx.ingress.kubernetes.io/use-regex: "true"

    # Rewrite the captured part of the regex (.*) back onto the request.
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: synchat.internal
    http:
      paths:
      - path: /(.*)             # regex capture group
        pathType: ImplementationSpecific
        backend:
          service:
            name: web-service
            port:
              number: 80

  - host: synchatapi.internal
    http:
      paths:
      - path: /(.*)             # keeps /v1/messages, /healthz, etc.
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-service
            port:
              number: 80

