apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - name: synergychat-api
        image: bootdotdev/synergychat-crawler:latest
        env:
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: API_PORT
